import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Roboto } from 'next/font/google';
import localFont from 'next/font/local'
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto"
})

const integralCF = localFont({
  src: "../fonts/Fontspring-DEMO-integralcf-regular.otf",
  variable: "--font-integral"
})
const satoshiRegular = localFont({
  src: "../fonts/Satoshi-Regular.woff",
  variable: "--font-Satoshi"
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${integralCF.variable} ${satoshiRegular.variable}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
